const currenciesList = [
  { name: "United States Dollar", symbol: "$" },
  { name: "Pakistan", symbol: "Rs" },
  { name: "Euro", symbol: "€" },
  { name: "British Pound Sterling", symbol: "£" },
  { name: "Japanese Yen", symbol: "¥" },
  { name: "Indian Rupee", symbol: "₹" },
  { name: "Australian Dollar", symbol: "A$" },
  { name: "Canadian Dollar", symbol: "C$" },
  { name: "Swiss Franc", symbol: "CHF" },
  { name: "Chinese Yuan", symbol: "¥" },
  { name: "Singapore Dollar", symbol: "S$" },
  { name: "Mexican Peso", symbol: "$" },
  { name: "Brazilian Real", symbol: "R$" },
  { name: "Russian Ruble", symbol: "₽" },
  { name: "South African Rand", symbol: "R" },
  { name: "South Korean Won", symbol: "₩" },
  { name: "New Zealand Dollar", symbol: "NZ$" },
  { name: "Swedish Krona", symbol: "kr" },
  { name: "Norwegian Krone", symbol: "kr" },
  { name: "Danish Krone", symbol: "kr" },
  { name: "Polish Zloty", symbol: "zł" },
  { name: "Turkish Lira", symbol: "₺" },
  { name: "Indonesian Rupiah", symbol: "Rp" },
  { name: "Malaysian Ringgit", symbol: "RM" },
  { name: "Philippine Peso", symbol: "₱" },
  { name: "Thai Baht", symbol: "฿" },
  { name: "United Arab Emirates Dirham", symbol: "د.إ" },
  { name: "Saudi Riyal", symbol: "ر.س" },
  { name: "Egyptian Pound", symbol: "£" },
  { name: "Colombian Peso", symbol: "$" },
  { name: "Chilean Peso", symbol: "$" },
  { name: "Argentine Peso", symbol: "$" },
  { name: "Israeli New Shekel", symbol: "₪" },
  { name: "Hong Kong Dollar", symbol: "HK$" },
  { name: "Taiwan Dollar", symbol: "NT$" },
  { name: "Vietnamese Dong", symbol: "₫" },
  { name: "Bahraini Dinar", symbol: ".د.ب" },
  { name: "Omani Rial", symbol: "ر.ع." },
  { name: "Kuwaiti Dinar", symbol: "د.ك" },
  { name: "Qatari Rial", symbol: "ر.ق" },
  { name: "Jordanian Dinar", symbol: "د.ا" },
  { name: "Sri Lankan Rupee", symbol: "රු" },
  { name: "Pakistani Rupee", symbol: "₨" },
  { name: "Bangladeshi Taka", symbol: "৳" },
  { name: "Hungarian Forint", symbol: "Ft" },
  { name: "Czech Koruna", symbol: "Kč" },
  { name: "Romanian Leu", symbol: "lei" },
  { name: "Ukrainian Hryvnia", symbol: "₴" },
  { name: "Kazakhstani Tenge", symbol: "₸" },
  { name: "Kenyan Shilling", symbol: "KSh" },
  { name: "Ugandan Shilling", symbol: "USh" }
];

export default currenciesList;